config/routes.rb
Rails.application.routes.draw do
  resources :shops
  post 'shops/liked', to: "shops#liked"
  post 'shops/disliked', to: "shops#disliked"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ApplicationRecord
    include PgSearch::Model

	 pg_search_scope :global_search,
    against: [:description, :address, :category, :name],
    using: {
      tsearch: {prefix: true}
    }
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  skip_before_action :verify_authenticity_token

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    if params[:query]
      @shops = Shop.global_search(params[:query])
    else
    @shops = Shop.all
  end
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  def liked
    @shop = Shop.find(params[:id])
    @shop.liked = true
    @shop.save!
        respond_to do |format|

    format.json { render :show, status: :created, location: @shop }
end
  end


   def disliked
    @shop = Shop.find(params[:id])
    @shop.liked = false
    @shop.save!
        respond_to do |format|

    format.json { render :show, status: :created, location: @shop }
end
  end


  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :address, :address_cn, :description, :description_cn, :image_url, :open_time, :close_time, :phone, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :address_cn %>
    <%= form.text_field :address_cn %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :description_cn %>
    <%= form.text_field :description_cn %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :open_time %>
    <%= form.time_select :open_time %>
  </div>

  <div class="field">
    <%= form.label :close_time %>
    <%= form.time_select :close_time %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Shops</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Address cn</th>
      <th>Description</th>
      <th>Description cn</th>
      <th>Open time</th>
      <th>Close time</th>
      <th>Phone</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.address %></td>
        <td><%= shop.address_cn %></td>
        <td><%= shop.description %></td>
        <td><%= shop.description_cn %></td>
        <td><%= shop.open_time %></td>
        <td><%= shop.close_time %></td>
        <td><%= shop.phone %></td>
        <td><%= shop.category %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @shop.address %>
</p>

<p>
  <strong>Address cn:</strong>
  <%= @shop.address_cn %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shop.description %>
</p>

<p>
  <strong>Description cn:</strong>
  <%= @shop.description_cn %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @shop.image_url %>
</p>

<p>
  <strong>Open time:</strong>
  <%= @shop.open_time %>
</p>

<p>
  <strong>Close time:</strong>
  <%= @shop.close_time %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @shop.phone %>
</p>

<p>
  <strong>Category:</strong>
  <%= @shop.category %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>